version: "3.8"

services:
  backend:
    container_name: teacher_student_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: teacher_student_mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: 11111111
      DB_NAME: teacher_student_db
    depends_on:
      - mysql
    command: npm run dev

  mysql:
    container_name: teacher_student_mysql
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 11111111
      MYSQL_DATABASE: teacher_student_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 11111111
    ports:
      - "3306:3306"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./database/data:/var/lib/mysql
